name = "PolynomialRoots"
uuid = "3a141323-8675-5d76-9d11-e1df1406c778"
authors = ["Mosè Giordano <mose@gnu.org>"]
version = "0.2.0"

[compat]
julia = "≥ 0.7.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
